### ISSUE TITLE
Learning Mesh-Based Simulation with Graph Networks Code 

### ISSUE THREAD

**Issue by asadabbas09** [deepmind/deepmind-research#101]
Do you plan to release code for MeshGraphNets (Learning Mesh-Based Simulation with Graph Networks 
 https://arxiv.org/pdf/2010.03409.pdf) in the near future?

Thanks for awesome work.

**Comment by quetil** [comment]
Looking forward to!

**Comment by virajone** [comment]
I'm really looking forward to trying it out as well ! Hope it's made available soon.

**Comment by mburaksayici** [comment]
Looking forward to it!

**Comment by DrTtnk** [comment]
Please, let me make a Blender addon :D

**Comment by adsau59** [comment]
is it out yet?

**Comment by adsau59** [comment]
https://github.com/deepmind/deepmind-research/tree/master/meshgraphnets
