### ISSUE TITLE
[Causal Inference] Erroneous cut and crit in first Interventions example?

### ISSUE THREAD

**Issue by tjohnson250** [deepmind/deepmind-research#108]
This cell: https://colab.research.google.com/github/deepmind/deepmind_research/blob/master/causal_reasoning/Causal_Reasoning_in_Probability_Trees.ipynb#scrollTo=z4PLcgN5_Vm5&line=5&uniqifier=1

in Section 6. Interventions has the following code:
```
print('Original:')
display(pt.show(show_prob=True, cut=cut, crit=crit))
```

However, neither a cut or critical set is  defined for the tree at the start of this example. I removed `, cut=cut, crit=crit` in my version.

**Comment by saran-t** [comment]
Resolved in 5b261680f3158758744ed60e4c882a082b9b2e65
