### ISSUE TITLE
Gradient descent

### ISSUE THREAD

**Issue by es15326** [deepmind/deepmind-research#127]
Hello.

Where is the gradient descent part of the paper?

**Comment by Augustin-Zidek** [comment]
Do you mean the AlphaFold gradient descent algorithm? 

Unfortunately, we decided to not open-source it. 

If you are looking into re-implementing it, the procedure is documented in the [Nature paper](https://rdcu.be/b0mtx) (see the "Structure realization by gradient descent" paragraph under the Methods section and also the [supplementary information](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-019-1923-7/MediaObjects/41586_2019_1923_MOESM1_ESM.pdf)).

**Comment by ValZapod** [comment]
So, it is now published?? https://github.com/deepmind/alphafold
