### ISSUE TITLE
Open Source the entire AlphaFold pipeline?

### ISSUE THREAD

**Issue by cement-head** [deepmind/deepmind-research#129]
This is exciting, but kinda not without the _entire_ pipeline open-sourced and available for wide usage.  Would you (all) consider making this available - rather than EUs having to best-guess how it was all done?  Thx

**Comment by Augustin-Zidek** [comment]
Sorry, we’re unable to open source the data and minimisation parts of the pipeline. However, the Methods section in the AlphaFold Nature paper (https://rdcu.be/b0mtx) should provide sufficient amount of details to enable reimplementation. I believe there are also open-source AlphaFold reimplementation available on GitHub.

**Comment by monkollek** [comment]
@cement-head if you are interested I implemented the protein folding part of the pipeline during the holiday break.
https://github.com/leklab/alphafoldv1
as I was interested in reproducing (or close to it) for some of the figures in the Nature publication.
