### ISSUE TITLE
Running alphafold_casp13 on Windows

### ISSUE THREAD

**Issue by L4rgus** [deepmind/deepmind-research#130]
Hey!

First of, I'm a newbie. And while alphafold_casp13 was running on my Linux, I was wondering if I could do that on Windows as well.
If yes, what changes do I have to do on the source files. Is it enough to just re-write the **run_eval.sh** to batch?

Another question: is there an easy way to convert the result pickle files to pdb format?

Thank you!

**Comment by Augustin-Zidek** [comment]
Hi,

We never tested AlphaFold never on Windows, so unfortunately I am not sure. I saw some people being able to run it using WSL, but they had to change some of the paths (and possibly other things) in the `run_eval.sh` script. See e.g. issues https://github.com/deepmind/deepmind-research/issues/50 and https://github.com/deepmind/deepmind-research/issues/75. However, I recommend running AlphaFold on Linux or in a virtual machine running Linux.

> Is there an easy way to convert the result pickle files to pdb format

The output pickle contains just the distogram, not the structure, it is therefore impossible to directly convert it to PDB. You would have to run the minimisation algorithm described in our paper (https://rdcu.be/b0mtx) to get the atom coordinates and then convert those to PDB format.
