### ISSUE TITLE
aatype feature

### ISSUE THREAD

**Issue by LivC182** [deepmind/deepmind-research#131]
Dear Madame/Sir,

The aatype feature (Lx21) is computed per amino acid, but it needs to be transformed to an LxLxN tensor to be concatenated with the rest of input features. 

For each ij aa pair, do you include the aa type for both i and j ending up with a LxLx42 tensor or are you only using the encoding for either i or j and repeat them along rows/colums ending up with LxLx21?

**Comment by Augustin-Zidek** [comment]
You are correct, we end up with an `L × L × 42` tensor for the `aatype` in the 2D features, i.e. the location `(i, j)` has the `aatype` for both `i` and `j`.
