### ISSUE TITLE
alphafold pickle files use python 2

### ISSUE THREAD

**Issue by aangelopoulos** [deepmind/deepmind-research#138]
Minor bug in the alphafold v1 distogram release.
The contacts/TARGET.pickle files in the released data were pickled using python 2, but the pickle default encodings changed between python2 and python3. So, the pickled data must be read with the following somewhat obtuse syntax when using python3:

```
    with open(contacts/TARGET.pickle, "rb") as f:
        loaded = pickle.load(f, encoding="latin1")
```

Given the requirements of this repository list python 3.6+, the pickles should be in the python3 format.

You can fix this problem by using the technique described here: https://rebeccabilbro.github.io/convert-py2-pickles-to-py3/
I have done this myself so if it is helpful I can share the converted files.

**Comment by Augustin-Zidek** [comment]
Hi Anastasios, 

good catch, thank you. I will clarify that in the documentation and close this issue once the README has been updated.

**Comment by aangelopoulos** [comment]
Happy to help!

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/deepmind/deepmind-research/commit/e7cd4f32a3b6508e2d950cd3e911abd6255d53fe. Thanks again and happy New Year.
