### ISSUE TITLE
AlphaFoldv1 code to produce folded structures as PDB?

### ISSUE THREAD

**Issue by monkollek** [deepmind/deepmind-research#158]
@Augustin-Zidek given the massive advancements in AlphaFold 2 making AlphaFoldv1 from CASP13 obsolete, are there plans to release the rest of the AlphaFoldv1 pipeline? As this still would be good for learning purposes for those that are interested.

I have implemented code to do the folding from the distance and torsion probabilities that will work with the pickle files outputted and reproduced Figures 3A and 3B in the Nature publication. 
https://github.com/leklab/alphafoldv1

However, it would be cool to see the AlphaFold team's implementation used in CASP13.

Thanks!

**Comment by Augustin-Zidek** [comment]
Hi Monkol, sorry, we don't have plans to release the rest of the AlphaFold 1 pipeline.
