### ISSUE TITLE
For NCBI technology Development?

### ISSUE THREAD

**Issue by calebhaines99** [deepmind/deepmind-research#168]

**Comment by Augustin-Zidek** [comment]
This issue seems to be related to AlphaFold, however, I am unsure how to answer it without more context. Could you provide more details?

**Comment by Augustin-Zidek** [comment]
Closing because there wasn't any activity. Feel free to reopen.

**Comment by calebhaines99** [comment]
I am currently unfamiliar with the patterns in which synapses form in the
brain but as a physics researcher I am highly concerned by the fact that my
synapsing cannot be directly imaged , graphed and modified so that I am
able to comfortably and confidently say that as long as some sort of action
or some sort of quantum algorithm is introduced in a certain way across all
of the possible synapse paths , that my neurons are not at risk of being
overused , under used or otherwise deemed inefficient or at risk of
unnecessary degradation. I am expecting that such an algorithm will act as
a translational unit in that quantum processes will be able to signal , to
my self , if there is any extraordinary wish for modifying the limitations
set forth by the quantum synapse protective algorithm that is installed.
This above process will most likely be due to weather factors.
