### ISSUE TITLE
[Question] Will the pre-trained model weights be released for the NF-Nets?

### ISSUE THREAD

**Issue by smj007** [deepmind/deepmind-research#169]
Would be really helpful if the weight files for the trained models are provided soon, for fine-tuning on other downstream tasks. Thanks!

**Comment by paulgavrikov** [comment]
I would second, smj007!

**Comment by Biki-das** [comment]
It has been update with the current modules and changes have been made, the
code written below has been checked with 10 edge cases

func GetCustomer(c *gin.Context) {
  t, _ := template.ParseFiles("index.html")
  t.Execute(c.Writer, nil)
  customerIdString := c.Param("id")  //taking the id from url
  customerId, err := strconv.Atoi(customerIdString)
  mongoSession := config.ConnectDb()
  collection := mongoSession.DB("customer").C("customercollection")
  pipeline := []bson.M{
    bson.M{"$match": bson.M{"_id": customerId}},
    bson.M{"$lookup": bson.M{"from" : "address", "localField" : "_id",
"foreignField": "user_id","as": "address" }},
    // bson.M{"$project":bson.M{"_id":0}}
  }
  pipe := collection.Pipe(pipeline)
  resp := []bson.M{}
  err = pipe.All(&resp)
  if err != nil {
     fmt.Println("Errored: %#v \n", err)
  }
 c.JSON(200, gin.H{"data": resp})
}

**_ the code above uses a low dynamic memory and has a array length to
determine the subset values with the local memory adress

**Comment by ajbrock** [comment]
Hi everyone, the weights for pre-trained NFNet models are now available.

**Comment by smj007** [comment]
Thanks! @ajbrock

**Comment by heytitle** [comment]
@ajbrock  If I'm not mistaken,  the statistics in [1]'s Table 2 were averaged from three model instances (trained with three different random seeds). May I ask whether you happen to (or plan) to release also the other two instances of each variant as well?

[1]: https://arxiv.org/pdf/2102.06171.pdf
