### ISSUE TITLE
alphafold-casp13 other protein dataset question

### ISSUE THREAD

**Issue by Planet-KIM** [deepmind/deepmind-research#183]
- Do you not support other protein besides casp13 dataset?
- I want to use covid 19 protein(SARS-CoV-2) on alphafold_casp13 project. Does not support it? 
- Give me the solutions please.

**Comment by Augustin-Zidek** [comment]
Hi,

> Do you not support other protein besides casp13 dataset?
Unfortunately, we don't. See https://github.com/deepmind/deepmind-research/tree/master/alphafold_casp13#setup or https://github.com/deepmind/deepmind-research/issues/28 for more information and workarounds.

> I want to use covid 19 protein(SARS-CoV-2) on alphafold_casp13 project. Does not support it?
As above, unfortunately no. However, we published COVID-19 structures folded using AlphaFold 2 (which is substantially better than AlphaFold 1 used in CASP13). You can find the predicted structures here: https://deepmind.com/research/open-source/computational-predictions-of-protein-structures-associated-with-COVID-19.

Hope this helps!
