### ISSUE TITLE
How to calculate GDT score in alphafold_casp13

### ISSUE THREAD

**Issue by Planet-KIM** [deepmind/deepmind-research#186]
Hello, I am a developer who is currently using the "alphafold_casp13 project".
I have some questions. Can you help me this problem.
- Now i using casp13 data. "output rr file" on contacts folder. 
- But,  I want know GDT score  on casp13 data (ex: T1019v1 GDT score)
- Please, If you have solutions. Can you teach me this problem.

**Comment by Augustin-Zidek** [comment]
I recommend taking a look at the GDT description here: https://foldit.fandom.com/wiki/GDT and an implementation here: https://bougui505.github.io/2017/07/13/global_distance_test_(gdt)_and_longest_continuous_segments_(lcs)_with_python.html.

Note that the RR file is the contact map which is not used for GDT calculation -- GDT is a metric between the ground truth atom coordinates and the predicted coordinates. You would therefore typically calculate GDT using the ground truth and the predicted PDB. 

However, the open-sourced code in this repository unfortunately doesn't give you the final PDB -- you will have to implement the gradient descent method to produce the PDB based on the distogram as described in our Nature paper.

I hope this helps.

**Comment by Biki-das** [comment]
Will be looking to this soon!!!
Plz reply me

**Comment by Planet-KIM** [comment]
@Augustin-Zidek Thank you for give the solution.
I give you one question.
- Doesn't open final PDB pipeline on this project(alphafold_casp13)?
- The Nature paper open 'final pdb pipeline' solution or algorithm?
