### ISSUE TITLE
What is the reason for crop the sequence?

### ISSUE THREAD

**Issue by Planet-KIM** [deepmind/deepmind-research#191]
- Now i test the alphafold_casp13 project.
- Now i don't understand crop the sequence. ( Why crop the sequence?)
- Can you teach me the reason?( I want to know this issue)

**Comment by Augustin-Zidek** [comment]
Hi,

we crop the the sequence into smaller chunks for multiple reasons:
1. To make it possible to work with proteins of different lengths. By cropping to a fixed length and then assembling those together, everything can have static shapes.
2. To fit easily into the GPU ram. The memory consumption of our networks is at least quadratic with the sequence length, hence large proteins would cause OOM issues.
3. To enable efficient training and batching.

**Comment by Planet-KIM** [comment]
@Augustin-Zidek  Thank you for relpy this issue.
