### ISSUE TITLE
Unfiltered DDPM-generated data

### ISSUE THREAD

**Issue by LayneH** [deepmind/deepmind-research#213]
Hi @diegolascasas, @sgowal

Thank you for open-sourcing the code and data in the [adversarial robustness repo](https://github.com/deepmind/deepmind-research/tree/master/adversarial_robustness).

It seems that only the filtered DDPM-generated CIFAR10/CIFAR100 data is available. I wonder if you can provide the *unfiltered* data or the DDPM model used to generate data.

**Comment by sgowal** [comment]
Hi @LayneH ,

Thank you for your interest. The DDPM-generated data is only filtered to keep the classes balanced (the paper is not clear on this point and will be updated to reflect this).

For CIFAR-10, we used the checkpoint available online: https://github.com/hojonathanho/diffusion
For CIFAR-100, we have trained our own DDPM using the same settings than those used by Ho et al. on CIFAR-10 (we obtain an FID of 5.58 and IS of 10.82).

I hope this helps.
