### ISSUE TITLE
Example training script for KFAC?

### ISSUE THREAD

**Issue by connection-on-fiber-bundles** [deepmind/deepmind-research#228]
It mentions in https://github.com/deepmind/deepmind-research/blob/master/kfac_ferminet_alpha/README.md that there's an example training script using KFAC, whose link is broken. Could someone help fix the link or kindly provide a training script example?

**Comment by jsspencer** [comment]
See https://github.com/deepmind/deepmind-research/blob/master/kfac_ferminet_alpha/example.py
