### ISSUE TITLE
computing power required in alphafold1-casp13

### ISSUE THREAD

**Issue by shuningge** [deepmind/deepmind-research#231]
Dear Alphafold Team!

Sincerely sorry to reach out this way. I'm a researcher at MIT CSAIL and currently working on a project that hopes to examine computing power used in CASPs. I've tried many methods but wasn't able to find information about the amount of computation used/required by alphafold1 in CASP13. I am wondering if this is sth that could be shared.

Any advice is appreciated!

**Comment by Augustin-Zidek** [comment]
Hi, sorry for the late reply. We’d like to keep GitHub issues to software questions — please direct AlphaFold questions to alphafold@deepmind.com.
