### ISSUE TITLE
World edges not implemented in meshgraphnets?

### ISSUE THREAD

**Issue by isabellahuang** [deepmind/deepmind-research#249]
From the 'Learning Mesh-Based Simulation with Graph Networks' paper, 
```
For Lagrangian systems, we add world edges EW to the graph, to enable learning external dynamics such as (self-) collision and contact,which are non-local in mesh-space. World-space edges are created by spatial proximity: that is,
given a fixed-radius rW on the order of the smallest mesh edge lengths, we add a world edge between nodes i and j if |xi − xj | < rW, excluding node pairs already connected in the mesh.
```
The flag_simple domain uses a cloth model, which is a Lagrangian system. However, I don't see anywhere in the code that forms these world-space edges. The rW parameter, called 'collision_radius' in the `meta.json`, is also never used.

**Comment by tobiaspfaff** [comment]
flag_simple is a simplified dataset, and was created without remeshing and collision (you can see the cloth interpenetrating in some frames), and so it does not use world edges. The datasets using world edges are: FlagDynamic, SphereSimple, SphereDynamic, DeformingPlate.
To create world edges for those datasets, you can e.g. use scipy.spatial.KDTree.query_ball_point with the collision_radius from meta.json.

**Comment by diegolascasas** [comment]
Closing this issue now, feel free to reopen if you have any questions.

**Comment by FishWoWater** [comment]
I am wondering whether the world edges only connect nodes from the cloth or they can connect nodes where one is from the cloth and the other is from the obstacle. In the latter case, we should be able to model both collision and self-collision, right?
Looking forward to your reply, thanks! @diegolascasas @tobiaspfaff
