### ISSUE TITLE
What are the different types represented by different numbers in node type in meshgraphnets?

### ISSUE THREAD

**Issue by wxntech** [deepmind/deepmind-research#250]
Hi. I am glad to see the code of Learning mesh-based simulation with graph network published. Both the code and the article mention the use of node types as training data. But the specific node type numbers represent which types are not mentioned in the paper and README. In addition, how are these types obtained? This information is very important for the use of other data sets. I hope to provide more information on these aspects, thanks!

**Comment by tobiaspfaff** [comment]
The node types are:
NORMAL = 0
OBSTACLE = 1 (the sphere for sphere/cloth interaction)
AIRFOIL = 2
HANDLE = 3 (the fixed node for the flag example)
INFLOW = 4 
OUTFLOW = 5
WALL_BOUNDARY = 6 (the walls in CylinderFlow)
These types are very arbitrary, and a different assignment would work as well. The only important distinction is whether nodes are boundary nodes, as nodes with fixed Dirichlet boundary conditions can be overwritten during rollout.
