### ISSUE TITLE
The difference between water and sand

### ISSUE THREAD

**Issue by orange-eng** [deepmind/deepmind-research#251]
Hello, I am learning your code "learning to simulate". My question is, for dataset "WaterRamps" and "Sand", there are some differences in metadata.json. But how to get these settings in metadata.json?

**Comment by alvarosg** [comment]
[This](https://github.com/deepmind/deepmind-research/blob/3eddada361629e603897a58caa901ebccc1167da/learning_to_simulate/train.py#L428) is the function that we are using to load the metadata, hope this helps!

**Comment by yq60523** [comment]
> [This](https://github.com/deepmind/deepmind-research/blob/3eddada361629e603897a58caa901ebccc1167da/learning_to_simulate/train.py#L428) is the function that we are using to load the metadata, hope this helps!

Hi, sorry to disturb you again.
I want to know how to generate the metadata.json with my own dataset. Could you share the code? Or share the detailed meaning about the 'bounds', 'sequence_length', 'default_connectivity_radius', 'dim', 'dt', 'vel_mean', 'vel_std', 'acc_mean', 'acc_std'? Some of them are cleared, but the detailed calculation isn't known.
