### ISSUE TITLE
Masked Language Modelling Imports Failing

### ISSUE THREAD

**Issue by Jadiker** [deepmind/deepmind-research#257]
When running all cells in this [colab]( https://colab.research.google.com/github/deepmind/deepmind_research/blob/master/perceiver/colabs/masked_language_modelling.ipynb) from [here](https://github.com/deepmind/deepmind-research/tree/master/perceiver) I get the following error:

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-7-a35f06e052de> in <module>()
>       8 import pickle
>       9 
> ---> 10 from perceiver import perceiver, position_encoding, io_processors, bytes_tokenizer
> 
> ImportError: cannot import name 'bytes_tokenizer' from 'perceiver' (/content/perceiver/__init__.py)
> 
> ---------------------------------------------------------------------------

I've looked at #254 and added those lines, but they don't seem to help in this case.

How can I run the code in the colab?

**Comment by lkhphuc** [comment]
`!wget -O /content/perceiver/bytes_tokenizer.py https://raw.githubusercontent.com/deepmind/deepmind-research/master/perceiver/bytes_tokenizer.py`

**Comment by fding** [comment]
Thanks for reporting this issue! @lkhphuc is right -- that line was missing from the Colab. This fix has now been applied to the the notebook.
