### ISSUE TITLE
Perceiver IO: Optical Flow Patch weighting

### ISSUE THREAD

**Issue by JOBR0** [deepmind/deepmind-research#259]
In the optical_flow colab the flow for the full sized image is calculated by predicting patches of fixed size and then stitching them together. 
In compute_optical_flow weights are calculated for each patch:

`weights_x, weights_y = jnp.meshgrid(jnp.arange(patch_size[1]), jnp.arange(patch_size[0]))`
 `weights = jnp.minimum(weights_x, weights_y)[jnp.newaxis, :, :,jnp.newaxis]`

these look something like this for a 3x4 patch:

[[0 0 0 0]
 [0 1 1 1]
 [0 1 2 2]]

Is there a reason why the pixels at the bottom right have higher weights?

**Comment by fding** [comment]
Thanks for reporting this issue. The weights were intended to represent the distance from the edge of the patch to give greater weight for flow from the center of the patch. This has now been fixed.
