### ISSUE TITLE
Implementation For World Edges In MeshgraphNets

### ISSUE THREAD

**Issue by FishWoWater** [deepmind/deepmind-research#275]
The provided `meshgraphnets` implementation seems to be a simplified one. I have two questions on this:
1. Whether the world edges only connect nodes from the cloth or they can connect nodes where one is from the cloth and the other is from the obstacle. In the latter case, we should be able to model both collision and self-collision, right?
2. I am not familiar with tensorflow, so I'd like to ask whether implementation like this is ok
```
collision_radius = 0.05
model_collision = False 
if 'MODEL_COLLISION' in os.environ and os.environ['MODEL_COLLISION'] == 'True':
    model_collision = True 
    print('world edges added')

class Model(snt.AbstractModule):
  """Model for static cloth simulation."""

  def __init__(self, learned_model, name='Model'):
    super(Model, self).__init__(name=name)
    with self._enter_variable_scope():
      self._learned_model = learned_model
      self._output_normalizer = normalization.Normalizer(
          size=3, name='output_normalizer')
      self._node_normalizer = normalization.Normalizer(
          size=3+common.NodeType.SIZE, name='node_normalizer')
      self._edge_normalizer = normalization.Normalizer(
          size=7, name='edge_normalizer')  # 2D coord + 3D coord + 2*length = 7
      self._world_edge_normalizer = normalization.Normalizer(
          size=4, name='world_edge_normalizer') # 3D coord + length = 4

  def _build_graph(self, inputs, is_training):
    """Builds input graph."""
    # construct graph nodes
    velocity = inputs['world_pos'] - inputs['prev|world_pos']
    node_type = tf.one_hot(inputs['node_type'][:, 0], common.NodeType.SIZE)
    node_features = tf.concat([velocity, node_type], axis=-1)

    # construct graph edges
    senders, receivers = common.triangles_to_edges(inputs['cells'])
    relative_world_pos = (tf.gather(inputs['world_pos'], senders) -
                          tf.gather(inputs['world_pos'], receivers))
    relative_mesh_pos = (tf.gather(inputs['mesh_pos'], senders) -
                         tf.gather(inputs['mesh_pos'], receivers))
    edge_features = tf.concat([
        relative_world_pos,
        tf.norm(relative_world_pos, axis=-1, keepdims=True),
        relative_mesh_pos,
        tf.norm(relative_mesh_pos, axis=-1, keepdims=True)], axis=-1)

    mesh_edges = core_model.EdgeSet(
        name='mesh_edges',
        features=self._edge_normalizer(edge_features, is_training),
        receivers=receivers,
        senders=senders)

    # construct distance matrix 
    world_pos = inputs['world_pos']
    dists = tf.sqrt((tf.reduce_sum(tf.pow(world_pos, 2), axis=-1, keepdims=True) +
            tf.reduce_sum(tf.pow(world_pos, 2), axis=-1) - 
            2 * tf.matmul(world_pos, tf.transpose(world_pos, (1, 0)))))
    meshmask_indices = tf.stack([senders, receivers], axis=-1)
    meshmask = tf.scatter_nd(meshmask_indices, tf.multiply(tf.ones(tf.shape(senders)[0]), 1e10), dists.shape)
    meshmask_indices2 = tf.stack([receivers, senders], axis=-1)
    meshmask2 = tf.scatter_nd(meshmask_indices2, tf.multiply(tf.ones(tf.shape(senders)[0]), 1e10), dists.shape)

    dists_final = tf.add(tf.add(tf.add(dists, meshmask), meshmask2), tf.multiply(tf.eye(tf.shape(dists)[0]), 1e10))
    dists_mask = tf.where(dists_final < collision_radius)
    u = tf.gather(dists_mask, 0, axis=-1); v = tf.gather(dists_mask, 1, axis=-1)
    world_senders = tf.concat([u, v], axis=0); world_receivers = tf.concat([v, u], axis=0)

    w_relative_world_pos = (tf.gather(inputs['world_pos'], world_senders) - 
                           tf.gather(inputs['world_pos'], world_receivers))
    sess = tf.Session()
    print(sess.run(world_senders).shape[0], "world senders exist")

    world_edge_features = tf.concat([
        w_relative_world_pos, 
        tf.norm(w_relative_world_pos, axis=-1, keepdims=True)], axis=-1)

    world_edges = core_model.EdgeSet(
        name='world_edges', 
        features=self._world_edge_normalizer(world_edge_features, is_training), 
        receivers=world_receivers, 
        senders=world_senders)

    return core_model.MultiGraph(
        node_features=self._node_normalizer(node_features, is_training),
        edge_sets=[mesh_edges, world_edges] if model_collision else [mesh_edges])
```

Highly appreciate your thoughts, thanks! @tobiaspfaff @diegolascasas

**Comment by robertreaney** [comment]
Hey did you get anywhere with this? I'm starting out on this endeavor as well.

**Comment by FishWoWater** [comment]
@robertreaney I am not sure whether the implementation agrees with the idea described in the paper; but I validated it with a numpy version and found them equivalent; I adpoted my implementation on my own data and it did work. Just pay attention to the choice of collision radius.

**Comment by alvarosg** [comment]
> how to deploy meshgraphnet on mobile devices

Unfortunately we have not explored mobile devices in this project.

**Comment by ylffan** [comment]
Hi,
I am also trying to implement the world edge feature. I used the ckdtree function from scipy and added edges between normal-normal and normal-obstacle nodes.

In the deforming plating example using rw=0.03, I found that the number of world edges (a few thousands) is similar to the number of mesh edges which reduce the training speed significantly (~12frames/sec). Moreover, the training aborted after 20k steps due to Out-of-Memory issue.

I have two questions:
1. does the world edge meant to have similar size at mesh edge? Or should the world edge only connects the between surface nodes (in the case of 3d solid models)?
2. I am using V100 gpu with 32G of RAM - will this be enough for training the deforming plate example?

Thank you so much for your help!

**Comment by ylffan** [comment]
hi @alvarosg 
thanks so much for your clarification!
yes, I did exclude the node pairs already exist in the mesh. As shown in the figure below (rw=0.03), the white edges are the added world edges which is around 1.6k and the number of mesh edges is around 4.3k. There are a lot of world edges cluster in regions with finer mesh.
![Screenshot 2022-02-10 103435](https://user-images.githubusercontent.com/60798575/153441258-fa0de38f-079b-425d-a6e7-af1a89852d9b.png)

Now the main problem I have is the training stops around 20k steps hitting OOM error. If the world edges I shown above seems valid and it has been successfully tested on V100 GPU, maybe my implementation handles GPU memory incorrectly or some memory leak issue? I am new to tensorflow and would appreciate if you can take a look at my implementation and see if there is any obvious problem causing this OOM error. (I have spent quite a while to debug this memory issue but still couldn't figure it out.) Thanks so much for your help!

---------------------------- world edge implementation -------------------------------------------------------
I modified the _build_graph function in the cloth_model.py
```
  def _build_graph(self, inputs, is_training):
    """Builds input graph."""
    # construct graph nodes
    node_type = tf.one_hot(inputs['node_type'][:, 0], common.NodeType.SIZE)
    node_features = node_type

    # construct graph edges

    tets = inputs['cells']
    faces = tf.concat([tets[:, 0:3],
                       tets[:, 1:4],
                       tf.stack([tets[:, 2], tets[:, 3], tets[:, 0]], axis=1),
                       tf.stack([tets[:, 3], tets[:, 0], tets[:, 1]], axis=1)], axis=0)
    
    senders, receivers, meshEdges = common.triangles_to_edges(faces)
    meshEdges = tf.reverse(meshEdges, [1])
    
    added_edges = tf.numpy_function(common.close_pairs_ckdtree, [inputs['world_pos'], 0.03], [tf.int32])[0]
    added_edges = tf.ensure_shape(added_edges, [None, 2])
    
    worldEdges = common.diff(added_edges, meshEdges)
    
    # remove the edges that does not connect to any NORMAL nodes
    map_nodetype = tf.squeeze(tf.gather(inputs['node_type'],worldEdges), -1)
    mask_WE = tf.reduce_any(tf.equal(map_nodetype,common.NodeType.NORMAL),-1)
    worldEdges_reduced = worldEdges[mask_WE]
    

    senders_W, receivers_W = common.edges_to_senders_receivers(worldEdges_reduced)
    
    relative_world_pos = (tf.gather(inputs['world_pos'], senders) -
                          tf.gather(inputs['world_pos'], receivers))
    relative_mesh_pos = (tf.gather(inputs['mesh_pos'], senders) -
                         tf.gather(inputs['mesh_pos'], receivers))
    
    relative_world_pos_W = (tf.gather(inputs['world_pos'], senders_W) -
                          tf.gather(inputs['world_pos'], receivers_W))
    
    edge_features = tf.concat([
        relative_world_pos,
        tf.norm(relative_world_pos, axis=-1, keepdims=True),
        relative_mesh_pos,
        tf.norm(relative_mesh_pos, axis=-1, keepdims=True)], axis=-1)
    
    edge_features_W = tf.concat([
        relative_world_pos_W,
        tf.norm(relative_world_pos_W, axis=-1, keepdims=True)], axis=-1)

    mesh_edges = core_model.EdgeSet(
        name='mesh_edges',
        features=self._edge_normalizer_M(edge_features, is_training),
        receivers=receivers,
        senders=senders)
    
    world_edges = core_model.EdgeSet(
        name='world_edges',
        features=self._edge_normalizer_W(edge_features_W, is_training),
        receivers=receivers_W,
        senders=senders_W)
    
    return core_model.MultiGraph(
        node_features=self._node_normalizer(node_features, is_training),
        edge_sets=[mesh_edges, world_edges])
```


And I added a few functions in common.py to calculate the world edges
```
def close_pairs_ckdtree(X, max_d):
    tree = ckdtree.cKDTree(X)
    pairs = tree.query_pairs(max_d)
    return np.ndarray.astype(np.array(list(pairs)),np.int32)

     
def diff(test,target):
    
    packed_test = tf.bitcast(test, tf.int64)
    packed_target = tf.bitcast(target, tf.int64)
    
    unique, idx = tf.setdiff1d(packed_test, packed_target)
    
    return tf.gather(test, idx)

def edges_to_senders_receivers(edges):
    
    receivers = tf.reduce_min(edges, axis=1)
    senders = tf.reduce_max(edges, axis=1)
    packed_edges = tf.bitcast(tf.stack([senders, receivers], axis=1), tf.int64)
    # remove duplicates and unpack
    unique_edges = tf.bitcast(tf.unique(packed_edges)[0], tf.int32)
    senders, receivers = tf.unstack(unique_edges, axis=1)
    # create two-way connectivity
    return (tf.concat([senders, receivers], axis=0),
            tf.concat([receivers, senders], axis=0))
```

**Comment by alvarosg** [comment]
Thanks for your reply.

> If the world edges I shown above seems valid

The world edges seem valid around the actuator/obstacle at the top, however I am bit surprised about all of the extra edges added around the front facing plate border. This border of the plate looks too jagged, and not round and smooth, like I would expect for the plate.

Are you visualizing a ground truth state from the dataset, or a model prediction form a longer trajectory? If it is the later, then what may be happening is that you may run into issues when producing model trajectories until your model predictions are better at preserving the overall plate shape.

Does your model run out of memory when performing a training step, or when generating a test trajectory?

As a side note just in case: in this dataset we also feed the model with the future position change of the obstacle for the next step (otherwise the model won't know where the obstacle is going). If this is not done, performance of the model may be not good enough.

**Comment by ylffan** [comment]
Thanks so much for this @alvarosg 

The plot is the ground truth "world_pos" after noise is applied - I think this is why it looks jaggy. I added the world edges based on the world_pos after noise being added so I thought this would be the right way to check/visualize the implementation. Was the world edges not added base on the noisy "world_pos"?

I also thought that the noise I add might be too much after seeing the shape, but I followed the noise parameter from the paper (noise = 0.003). (Also, from the paper, it says noise in the FLAGSIMPLE is 1e-3, but in the shared code it's set to 3e-3 .)

Yes, the model run out of memory during training it always stops after 21k of training which makes me think this is related to memory leak. The error message looks like this:
```
I0209 17:46:21.932535 140027369797440 basic_session_run_hooks.py:692] global_step/sec: 10.854
I0209 17:46:29.578360 140027369797440 run_model.py:92] Step 210000: Loss 0.222613
INFO:tensorflow:global_step/sec: 10.659
I0209 17:46:31.314347 140027369797440 basic_session_run_hooks.py:692] global_step/sec: 10.659
INFO:tensorflow:global_step/sec: 11.2546
I0209 17:46:40.199591 140027369797440 basic_session_run_hooks.py:692] global_step/sec: 11.2546
INFO:tensorflow:global_step/sec: 10.8681
I0209 17:46:49.400836 140027369797440 basic_session_run_hooks.py:692] global_step/sec: 10.8681
INFO:tensorflow:global_step/sec: 10.3916
I0209 17:46:59.023949 140027369797440 basic_session_run_hooks.py:692] global_step/sec: 10.3916
INFO:tensorflow:global_step/sec: 10.5584
I0209 17:47:08.495074 140027369797440 basic_session_run_hooks.py:692] global_step/sec: 10.5584
INFO:tensorflow:global_step/sec: 10.6846
I0209 17:47:17.854337 140027369797440 basic_session_run_hooks.py:692] global_step/sec: 10.6846
INFO:tensorflow:global_step/sec: 10.8178
I0209 17:47:27.098296 140027369797440 basic_session_run_hooks.py:692] global_step/sec: 10.8178
INFO:tensorflow:global_step/sec: 10.6755
I0209 17:47:36.465549 140027369797440 basic_session_run_hooks.py:692] global_step/sec: 10.6755
INFO:tensorflow:global_step/sec: 10.5443
I0209 17:47:45.949387 140027369797440 basic_session_run_hooks.py:692] global_step/sec: 10.5443
2022-02-09 17:47:58.139022: W tensorflow/core/common_runtime/bfc_allocator.cc:419] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.08GiB (rounded to 1162426368).  Current allocation summary follows.
2022-02-09 17:47:58.178822: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (256):   Total Chunks: 381, Chunks in use: 365. 95.2KiB allocated for chunks. 91.2KiB in use in bin. 1.7KiB client-requested in use in bin.
2022-02-09 17:47:58.178838: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (512):   Total Chunks: 1003, Chunks in use: 994. 506.0KiB allocated for chunks. 500.8KiB in use in bin. 497.0KiB client-requested in use in bin.
2022-02-09 17:47:58.178845: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (1024):  Total Chunks: 12, Chunks in use: 4. 16.0KiB allocated for chunks. 5.8KiB in use in bin. 5.5KiB client-requested in use in bin.
2022-02-09 17:47:58.178852: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (2048):  Total Chunks: 6, Chunks in use: 5. 13.8KiB allocated for chunks. 11.0KiB in use in bin. 9.5KiB client-requested in use in bin.
2022-02-09 17:47:58.178858: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (4096):  Total Chunks: 10, Chunks in use: 8. 45.5KiB allocated for chunks. 34.0KiB in use in bin. 34.0KiB client-requested in use in bin.
2022-02-09 17:47:58.178864: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (8192):  Total Chunks: 23, Chunks in use: 22. 213.8KiB allocated for chunks. 205.0KiB in use in bin. 194.4KiB client-requested in use in bin.
2022-02-09 17:47:58.178870: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (16384):         Total Chunks: 4, Chunks in use: 3. 85.5KiB allocated for chunks. 68.5KiB in use in bin. 56.3KiB client-requested in use in bin.
2022-02-09 17:47:58.178876: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (32768):         Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-02-09 17:47:58.178883: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (65536):         Total Chunks: 416, Chunks in use: 415. 27.25MiB allocated for chunks. 27.17MiB in use in bin. 26.47MiB client-requested in use in bin.
2022-02-09 17:47:58.178890: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (131072):        Total Chunks: 170, Chunks in use: 170. 31.76MiB allocated for chunks. 31.76MiB in use in bin. 31.57MiB client-requested in use in bin.
2022-02-09 17:47:58.178896: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (262144):        Total Chunks: 14, Chunks in use: 13. 4.99MiB allocated for chunks. 4.62MiB in use in bin. 2.44MiB client-requested in use in bin.
2022-02-09 17:47:58.178902: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (524288):        Total Chunks: 2, Chunks in use: 2. 1.41MiB allocated for chunks. 1.41MiB in use in bin. 1.41MiB client-requested in use in bin.
2022-02-09 17:47:58.178909: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (1048576):       Total Chunks: 45, Chunks in use: 45. 50.31MiB allocated for chunks. 50.31MiB in use in bin. 48.10MiB client-requested in use in bin.
2022-02-09 17:47:58.178915: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (2097152):       Total Chunks: 34, Chunks in use: 34. 101.35MiB allocated for chunks. 101.35MiB in use in bin. 101.35MiB client-requested in use in bin.
2022-02-09 17:47:58.178921: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (4194304):       Total Chunks: 1, Chunks in use: 1. 4.55MiB allocated for chunks. 4.55MiB in use in bin. 2.89MiB client-requested in use in bin.
2022-02-09 17:47:58.178928: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (8388608):       Total Chunks: 43, Chunks in use: 43. 488.88MiB allocated for chunks. 488.88MiB in use in bin. 475.60MiB client-requested in use in bin.
2022-02-09 17:47:58.178935: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (16777216):      Total Chunks: 4, Chunks in use: 3. 83.68MiB allocated for chunks. 64.35MiB in use in bin. 33.15MiB client-requested in use in bin.
2022-02-09 17:47:58.178942: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (33554432):      Total Chunks: 10, Chunks in use: 10. 361.45MiB allocated for chunks. 361.45MiB in use in bin. 331.46MiB client-requested in use in bin.
2022-02-09 17:47:58.178948: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (67108864):      Total Chunks: 1, Chunks in use: 1. 65.70MiB allocated for chunks. 65.70MiB in use in bin. 33.15MiB client-requested in use in bin.
2022-02-09 17:47:58.178954: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (134217728):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
2022-02-09 17:47:58.178961: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (268435456):     Total Chunks: 58, Chunks in use: 57. 28.68GiB allocated for chunks. 27.87GiB in use in bin. 27.79GiB client-requested in use in bin.
2022-02-09 17:47:58.207100: I tensorflow/core/common_runtime/bfc_allocator.cc:885] Bin for 1.08GiB was 256.00MiB, Chunk State:
2022-02-09 17:47:58.207123: I tensorflow/core/common_runtime/bfc_allocator.cc:891]   Size: 832.03MiB | Requested Size: 8B | in_use: 0 | bin_num: 20, prev:   Size: 33.15MiB | Requested Size: 33.15MiB | in_use: 1 | bin_num: -1
2022-02-09 17:47:58.207130: I tensorflow/core/common_runtime/bfc_allocator.cc:898] Next region of size 32079426304
2022-02-09 17:47:58.207138: I tensorflow/core/common_runtime/bfc_allocator.cc:905] InUse at 0x7f4c86000000 next 1 of size 256
```

Good to know about that the plate future position should be fed into the model - I didn't have this. I was able to generate trajectories from whenever the training was stopped but the performance was very poor - most of the time the obstacle penetrates the plate -  I thought it might be due to not enough training steps being run. Would you mind giving some insight on how to feed only the future position of the obstacle in the model?

**Comment by xenonlin** [comment]
> hi @alvarosg thanks so much for your clarification! yes, I did exclude the node pairs already exist in the mesh. As shown in the figure below (rw=0.03), the white edges are the added world edges which is around 1.6k and the number of mesh edges is around 4.3k. There are a lot of world edges cluster in regions with finer mesh. ![Screenshot 2022-02-10 103435](https://user-images.githubusercontent.com/60798575/153441258-fa0de38f-079b-425d-a6e7-af1a89852d9b.png)
> 
> Now the main problem I have is the training stops around 20k steps hitting OOM error. If the world edges I shown above seems valid and it has been successfully tested on V100 GPU, maybe my implementation handles GPU memory incorrectly or some memory leak issue? I am new to tensorflow and would appreciate if you can take a look at my implementation and see if there is any obvious problem causing this OOM error. (I have spent quite a while to debug this memory issue but still couldn't figure it out.) Thanks so much for your help!
> 
> ---------------------------- world edge implementation ------------------------------------------------------- I modified the _build_graph function in the cloth_model.py
> 
> ```
>   def _build_graph(self, inputs, is_training):
>     """Builds input graph."""
>     # construct graph nodes
>     node_type = tf.one_hot(inputs['node_type'][:, 0], common.NodeType.SIZE)
>     node_features = node_type
> 
>     # construct graph edges
> 
>     tets = inputs['cells']
>     faces = tf.concat([tets[:, 0:3],
>                        tets[:, 1:4],
>                        tf.stack([tets[:, 2], tets[:, 3], tets[:, 0]], axis=1),
>                        tf.stack([tets[:, 3], tets[:, 0], tets[:, 1]], axis=1)], axis=0)
>     
>     senders, receivers, meshEdges = common.triangles_to_edges(faces)
>     meshEdges = tf.reverse(meshEdges, [1])
>     
>     added_edges = tf.numpy_function(common.close_pairs_ckdtree, [inputs['world_pos'], 0.03], [tf.int32])[0]
>     added_edges = tf.ensure_shape(added_edges, [None, 2])
>     
>     worldEdges = common.diff(added_edges, meshEdges)
>     
>     # remove the edges that does not connect to any NORMAL nodes
>     map_nodetype = tf.squeeze(tf.gather(inputs['node_type'],worldEdges), -1)
>     mask_WE = tf.reduce_any(tf.equal(map_nodetype,common.NodeType.NORMAL),-1)
>     worldEdges_reduced = worldEdges[mask_WE]
>     
> 
>     senders_W, receivers_W = common.edges_to_senders_receivers(worldEdges_reduced)
>     
>     relative_world_pos = (tf.gather(inputs['world_pos'], senders) -
>                           tf.gather(inputs['world_pos'], receivers))
>     relative_mesh_pos = (tf.gather(inputs['mesh_pos'], senders) -
>                          tf.gather(inputs['mesh_pos'], receivers))
>     
>     relative_world_pos_W = (tf.gather(inputs['world_pos'], senders_W) -
>                           tf.gather(inputs['world_pos'], receivers_W))
>     
>     edge_features = tf.concat([
>         relative_world_pos,
>         tf.norm(relative_world_pos, axis=-1, keepdims=True),
>         relative_mesh_pos,
>         tf.norm(relative_mesh_pos, axis=-1, keepdims=True)], axis=-1)
>     
>     edge_features_W = tf.concat([
>         relative_world_pos_W,
>         tf.norm(relative_world_pos_W, axis=-1, keepdims=True)], axis=-1)
> 
>     mesh_edges = core_model.EdgeSet(
>         name='mesh_edges',
>         features=self._edge_normalizer_M(edge_features, is_training),
>         receivers=receivers,
>         senders=senders)
>     
>     world_edges = core_model.EdgeSet(
>         name='world_edges',
>         features=self._edge_normalizer_W(edge_features_W, is_training),
>         receivers=receivers_W,
>         senders=senders_W)
>     
>     return core_model.MultiGraph(
>         node_features=self._node_normalizer(node_features, is_training),
>         edge_sets=[mesh_edges, world_edges])
> ```
> 
> And I added a few functions in common.py to calculate the world edges
> 
> ```
> def close_pairs_ckdtree(X, max_d):
>     tree = ckdtree.cKDTree(X)
>     pairs = tree.query_pairs(max_d)
>     return np.ndarray.astype(np.array(list(pairs)),np.int32)
> 
>      
> def diff(test,target):
>     
>     packed_test = tf.bitcast(test, tf.int64)
>     packed_target = tf.bitcast(target, tf.int64)
>     
>     unique, idx = tf.setdiff1d(packed_test, packed_target)
>     
>     return tf.gather(test, idx)
> 
> def edges_to_senders_receivers(edges):
>     
>     receivers = tf.reduce_min(edges, axis=1)
>     senders = tf.reduce_max(edges, axis=1)
>     packed_edges = tf.bitcast(tf.stack([senders, receivers], axis=1), tf.int64)
>     # remove duplicates and unpack
>     unique_edges = tf.bitcast(tf.unique(packed_edges)[0], tf.int32)
>     senders, receivers = tf.unstack(unique_edges, axis=1)
>     # create two-way connectivity
>     return (tf.concat([senders, receivers], axis=0),
>             tf.concat([receivers, senders], axis=0))
> ```
Subject: Appreciation and Question about Your Code

Hi @ylffan!

Your code is incredibly helpful, and I've learned a lot from it.

I'm currently facing an issue with implementation of deforming plate, I've tried use your code, but I'm still having difficulty in defining the loss und _update function.

Would you mind sharing your code about them and let me know if you have any suggestions on how to resolve this issue?

Of course, I completely understand if you are busy or unable to help at the moment. Please take your time. 

ZX
