### ISSUE TITLE
MeshGraphNet Training Speed

### ISSUE THREAD

**Issue by dsconnol** [deepmind/deepmind-research#283]
Hey all! 

I'm currently looking to try and use MeshGraphNet as part of a research work, but I'm having a bit of difficulty with replicating the results. I'm currently working with an NVIDIA DGX Station with 4x 32Gb V100 GPUs and 40 cores  (Python 3.7.3, tensorflow-gpu 1.15.0, dm-sonnet 1.36). However, when I attempt to replicate the simple_flag training on 1x V100 GPU using the information presented in the readme (with nothing else running on the machine), I'm only getting ~3 steps/second. In addition, the GPU memory sits around 310Mb and 0% usage. For the 10 million training steps required in the presented paper this would result in about 37 days of training time. Is this the expected behaviour for this script? Is there anything you can think of that would significantly speed up results generation (e.g. maybe increasing the prefetch to avoid disk usage?)? If possible, I just want to replicate exactly what was done in the paper.  

Thanks for your help!
Dan C

**Comment by arjun-mani** [comment]
Hi @dsconnol, could you explain how you resolved this? I'm facing a similar issue of 0% GPU usage. Would really appreciate it, thanks.
