### ISSUE TITLE
Perceiver IO Training Script on Language

### ISSUE THREAD

**Issue by ShoufaChen** [deepmind/deepmind-research#284]
Hi,

Similar to https://github.com/deepmind/deepmind-research/issues/281,

do you have any plan to relase the training script for language model?

Thanks in advance.

**Comment by djaegle** [comment]
Hi ShoufaChen, thanks for your interest. We have no plans to release training scripts for language at the moment, as they depend heavily on our internal infrastructure.

**Comment by ShoufaChen** [comment]
Thanks all the way for your reply.
