### ISSUE TITLE
gpu support for curl

### ISSUE THREAD

**Issue by dhanajitb** [deepmind/deepmind-research#29]
Does CURL implementation have support GPU?
I am unable to run it entirely on GPU, and it is mostly running on the CPU.

**Comment by saehoonkim** [comment]
In my case, after editing tensorflow==1.14.0 in requirements.txt to tensorflow-gpu==1.14.0, it's able to be running on the GPU.

**Comment by diegolascasas** [comment]
Unfortunately there is no way of adding conditional dependencies on the requirements.txt file, so this is the way to go. Does it work for you?

I'll go ahead and close the issue, feel free to reopen it.
