### ISSUE TITLE
meshgraphnet: deforming plate dataset

### ISSUE THREAD

**Issue by amaleki2** [deepmind/deepmind-research#298]
I have postprocessed the "deforming plate" dataset and visualized a couple of examples which are significantly less visually appealing than the movies posted with the paper. I wanted to confirm if the movies have been post processed (e.g. using normal vectors, which are not provided in the dataset).

Here is a link to a couple of visualization
https://drive.google.com/file/d/10QVJheNBs4bNEUCg_LOaxxWbShISqDPJ/view?usp=sharing

Here is the snipet I used to post process the data.
 ```
import meshio
from dataset import load_dataset

data = load_dataset("deforming_plate", "test")
keys = data.output_classes.keys()
processed_data = {k: [] for k in keys}
for key in keys:
    for d in data:
        processed_data[key].append(d[key].numpy())

n = 0  # data instance
t_idx = 100   # timestep
points = np.array(processed_data["mesh_pos"][n])[0]
cells = np.array(processed_data["cells"][n])[0]
cells = [("quad", cells )]
point_data={"stress": processed_data["stress"][n][t_idx, :, 0], 
            "node_type": processed_data["node_type"][n][t_idx, :, 0]}
mesh = meshio.Mesh(points, cells, point_data=point_data)
mesh.write("data.vtk")
```

**Comment by amaleki2** [comment]
update: 
if you change "quad" to "tetra" in the code snippet, then the visualizations are correct.

**Comment by Zevrap-81** [comment]
hello,
how did u use this dataset without the hyperelastic model. since it is not created. or is it
could you also share with me how to use the code to use deforming plate dataset

**Comment by amaleki2** [comment]
I don't quite undertand your question. If you are wondering how I downloaded the data, I followed the instruction provided. I used the tag `deforming_plate` as instructed.
