### ISSUE TITLE
BoxBath dataset - Learning to Simulate Complex Physics with Graph Networks

### ISSUE THREAD

**Issue by JohnKond** [deepmind/deepmind-research#305]
Hello, 
im currently implementing my thesis in neural networks, and I want to recreate your BoxBath scene(cube interaction with water), but it seems there's not a BoxBath dataset in your GoogleApi storage. Could you provide the dataset you used for BoxBath domain?

Thanks a lot!

**Comment by philippe5572** [comment]
Hi,
      I have the same dilemma. Could you provide the WaterVortex and Ramps-Small dataset please?

Cheers..

**Comment by alvarosg** [comment]
Thanks for your message @JohnKond . We used the BoxBath dataset by [Li et al](https://arxiv.org/pdf/1810.01566.pdf), which is why we did not open source it (If I remember correct we requested the dataset directly from the authors).

**Comment by alvarosg** [comment]
Thanks for your message @philippe5572 . Unfortunately we run those generalizations settings (WaterVortex, Ramps-Small, Ramps-Large, Hourglass, MultiHippo) on the fly as a one-off example to demonstrate the qualitative performance over a variety of settings, but we do not have a serialized version of those in dataset form.

**Comment by philippe5572** [comment]
Thanks for the quick response @alvarosg. Would you be able to kindly share the code especially the one which generates the WaterVortex dataset, as I needed to conduct computational fluid dynamics simulation as part of my student-research experiment. If it's not possible to share the code, would you give me some pointers/directions on how to generate them preferably using open source code. 

Cheers..

**Comment by alvarosg** [comment]
Thanks @philippe5572 let's continue the discussion about what you need via email to corresponding author, and we'll see what we can do about that specific dataset.
