### ISSUE TITLE
Wikigraphs paper pretrained checkpoints

### ISSUE THREAD

**Issue by dxlong2000** [deepmind/deepmind-research#311]
Dear authors of the paper Wikigraphs,

I am currently trying to make some experiments on our dataset. Unfortunately, I couldn't be able to find any pretrained checkpoints. May I ask does it have any way for me to have the pre-trained checkpoints from you, or the checkpoints are not provided at this time?

Thank you & best regards,

**Comment by wanglouis49** [comment]
Hi Do Xuan, thank you for your interests in our work. Unfortunately, we do not have any plan to release the checkpoints at the moment. However, you may train the GNN-based transformer model in the paper using the default config, or the unconditional or BoW-based one by changing `model_type` to `text` or `bow2text`, respectively. Let me know if you have any problem doing that.
