### ISSUE TITLE
issue with downloading the datasets for learning_to_simulate

### ISSUE THREAD

**Issue by cyrillebreard** [deepmind/deepmind-research#312]
Use the following command to download:
wget -O datasets\WaterRamp\metadata.json https://storage.googleapis.com/learning-to-simulate-complex-physics/Datasets/WaterRamp/metadata.json

--2021-12-07 10:47:55--  https://storage.googleapis.com/learning-to-simulate-complex-physics/Datasets/WaterRamp/metadata.json
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.68.48, 142.250.68.80, 142.250.68.112, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.68.48|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-12-07 10:47:58 ERROR 403: Forbidden.

Any help ? 

Thanks

**Comment by alvarosg** [comment]
I think you may be missing a letter. The dataset name should be `WaterRamps`

**Comment by cyrillebreard** [comment]
OOPS yes indeed, so silly I am! Thanks for your reply. Now it is fine. Thanks again.

**Comment by RZZBlackMagic** [comment]
Hello, I would like to learn this model. Where can I download the relevant data set? Thanks

**Comment by RZZBlackMagic** [comment]
Hello, I would like to learn Graph Matching Networks. Where can I download the relevant data set?Thanks
