### ISSUE TITLE
Problem running DM21 simples

### ISSUE THREAD

**Issue by AMDALI** [deepmind/deepmind-research#325]
Hello,
why I had this message when I try to run the exemple with the DM21 :
mf._numint = dm21.NeuralNumInt(dm21.Functional.DM21)
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
WARNING:tensorflow:From /home/ali/venv/DM21/lib/python3.8/site-packages/tensorflow_hub/saved_model_lib.py:110: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
2022-02-02 13:36:25.141006: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> mf.kernel()
converged SCF energy = -128.870274298183
-128.87027429818272
I use Python V 3.8.10
Tensorflow CPU 2.7.0
machine configuration I5-4300U cpu with out NVIDIA gpu and 8 go ram.
thanks.

**Comment by jsspencer** [comment]
The messages are due to DM21 using the TensorFlow 1 API graph rather than TensorFlow 2. They will not affect the calculated results.
