### ISSUE TITLE
RETRO 

### ISSUE THREAD

**Issue by awehrs** [deepmind/deepmind-research#327]
Are there any plans to open source the RETRO implementation? I'm curious in particular how  the chunked cross attention was done in parallel across multiple retrieved documents. Great work, y'all.

**Comment by diegolascasas** [comment]
Hi @awehrs, thanks for your interest!

There is no plan to opensource the RETRO implementation right now. 
In case it's open sourced in the future it will be in its own repository, so make sure to check the DeepMind page for updates.
