### ISSUE TITLE
Hierarchical Perceiver code release? 

### ISSUE THREAD

**Issue by josephrocca** [deepmind/deepmind-research#332]
Hello, just wondering whether the HiP code (and pre-trained models?) are going to be released and if so, whether there's an ETA on that? Even a super rough estimate (e.g. "some time in the next 6 months") would be really handy to know. Thanks!

**Comment by joaoluiscarreira** [comment]
Hi Joseph. We plan to release source code late June/early July.

**Comment by marcomoldovan** [comment]
Just wanted to follow up on this, can we expect a code release for HiP anytime soon?

**Comment by josephrocca** [comment]
For those watching this issue, Joao has said via email that by the end of September there'll be a HiP code release via a different project, and that there's a chance the code for the original HiP will be released soon, but not totally sure as someone else is working on that.

**Comment by nevercast** [comment]
Hi all, has anyone seen any updates on this? Was the "other project" announced or released? 

Cheers,
Josh

**Comment by josephrocca** [comment]
I haven't seen anything yet. Joao has an active Twitter account, so it'll likely be announced there: https://twitter.com/joaocarreira If anyone sees an announcement, please post a comment here so all watchers of this issue will be notified.

**Comment by joaoluiscarreira** [comment]
Hi folks,

the other project will be announced next week, however the associated code release is delayed to the cvpr deadline. So sorry about this.

Joao

**Comment by josephrocca** [comment]
Hey @joaoluiscarreira wondering if there's a new ETA? Not to rush you at all! Just curious if you have a rough guess - even if it's several months away, but I understand if you don't have an estimate at this point. Please excuse my excitement/impatience 😅

**Comment by dmus** [comment]
And any new estimate? :)

**Comment by josephrocca** [comment]
Hey @joaoluiscarreira sorry (for the ping) wondering if that authorization has come through yet?

**Comment by joaoluiscarreira** [comment]
Hey Joseph,

yes! https://github.com/deepmind/hierarchical_perceiver/
Props to Skanda Koppula who did most of the work in open sourcing this.

Best,

Joao
