### ISSUE TITLE
incorrect m3a format in alphafold

### ISSUE THREAD

**Issue by aai97** [deepmind/deepmind-research#34]
When describing the [deletion_probability feature for alphafold](https://github.com/deepmind/deepmind-research/tree/master/alphafold_casp13#deletion_probability), you specify the fact that you use the m3a format from hhblits. 
To quote [hhblits' github on the m3a format](https://github.com/soedinglab/hh-suite/wiki#the-same-alignment-in-a3m):
> residues emitted by Match states of the HMM are in upper case, residues emitted by Insert states are in lower case and deletions are written -.

In the m3a format, the sequences of the MSA are not necessarily of equal length, and _deletions are denoted by "-"_, whereas _lowercase letters denote insertions_ and cause the disparities in sequence length:
```
A B C        Original sequence
A - E        Sequence where residue 2 was deleted, residue 3 was substituded
A d B C      Sequence where a residue d was inserted between residue 2 and 3. 
             Note that now the residue B no longer aligns with that of the original sequence.
```
This means your description of the deletion_probability feature makes no sense: not just should we count "-" rather than lowercase letters if we are looking for deletions, but aligning the residues by column makes no sense in the a3m format, since the lengths dont match.

Assuming that the name deletion_probability is not a misnomer, one has to instead remove all lowercase letters form the a3m MSA and then count the number of "-" per column to obtain the probability of a deletion of a particular residue in the MSA.

Is my reasoning here correct, or am I missing something important?

**Comment by huhlim** [comment]
I agree with your opinion. The description was strange to me for the same reason.

**Comment by Augustin-Zidek** [comment]
Hi, thanks for the feedback. You are right, the description of the `deletion_probability` feature wasn't correct, I fixed it and added a code snippet to show how we compute the `deletion_probability` feature to make it clearer.

On the insertion vs deletion comment: I agree that our naming is misleading -- we call them 'deleted' residues because they have to be deleted in order for the sequence to align to the query.

**Comment by aai97** [comment]
Thank you for the update.
