### ISSUE TITLE
About example for methane post on DM21

### ISSUE THREAD

**Issue by Eureka10shen** [deepmind/deepmind-research#347]
In the readme file of DM21, an example of methane atomization energy was post. It was told that the literature for atomization energy of methane is 420.42kcal/mol,. But when I search for it on CCCBDB benchmark, it was told that atomization energy of methane is 1642kj/mol (392.45kcal/mol) under 0K and 1663.3kj/mol (397.54kcal/mol) under 298K. I'm wondering where the 420.42kcal/mol literature data come from? https://cccbdb.nist.gov/ea2x.asp

**Comment by jsspencer** [comment]
420.42kcal/mol is the atomization energy (computed at W4 level of theory) from the GMTKN55 dataset. I think the value you quote from CCCBDB is experimental, which must be corrected to remove relativistic effects (pretty small) and zero point vibrational energy (not so small). With these terms accounted for, W4 agrees extremely well with experiment.

http://www.thch.uni-bonn.de/tc.old/downloads/GMTKN/GMTKN55/W4-11ref.html
https://pubs.acs.org/doi/10.1021/jp801805p

**Comment by Eureka10shen** [comment]
Does it mean that there is always zero-point deviation from experimental data the result cannot take account of when I want to calculate some new result by DM21? I want to quest for the generalization limit of DM21 hybrid by performing some tough task like transition-state barrier other than examples on the article.

**Comment by Eureka10shen** [comment]
Another question is why do you use the energy without zero-point correction rather than with it? I noticed that there are experimental data in W4 dataset. For example in the paper you post above, CH4 has 3 atomization energy benchmarks ---- TAE_e^a=420.42, TAE_e^b=420.20, TAE_0^c=392.46. Could you offer your reason for choosing the first one as benchmark? Thank you.

> Does it mean that there is always zero-point deviation from experimental data the result cannot take account of when I want to calculate some new result by DM21? I want to quest for the generalization limit of DM21 hybrid by performing some tough task like transition-state barrier other than examples on the article.

**Comment by jsspencer** [comment]
The first value is chosen (when creating the W4-08 dataset, not by us) as it is most directly comparable to calculations from non-relativistic methods. It is important to compare like-for-like -- e.g. when comparing theoretical and experimental data to account for contributions (such as ZPVE) not included at a given level of theory. This is not specific to DM21.

This forum is primarily for technical issues specific to our code, rather than general questions around quantum chemistry.
