### ISSUE TITLE
curl for omniglot stuck after Iteration 1999

### ISSUE THREAD

**Issue by dhanajitb** [deepmind/deepmind-research#35]
When running 
`PYTHONPATH=`pwd`/..:$PYTHONPATH python3 train_main.py --dataset='omniglot'
`
the code is stuck after iteration 2000:
```
I0301 12:30:59.622419 140350619187008 training.py:1115] Iteration 1999, Train batch purity: 1.000, Train elbo: 3810.632, Train kl y: 2.944, Train kl z: 67.379 n_active: 19
2020-03-01 12:31:08.276665: W ./tensorflow/core/framework/model.h:213] Encountered a stop event that was not preceded by a start event.
```
Is there some problem with the code or it takes too much time? It has been stuck for over 2 days now.

Also, is the purity same as the cluster accuracy which is mentioned in the paper?
Thank you.

**Comment by drao2** [comment]
Sorry for the delay, I didn't get a notification for this unfortunately.

That's odd; I've never seen that before (definitely not 2 days). But it may depend on experimental parameters and/or hardware used in the setup. Are your experimental parameters at the defaults? And is this on GPU or CPU?

Feel free to email me (contact details in the paper) to discuss further.

Re: your second point; yes - purity is the same as cluster accuracy.
