### ISSUE TITLE
Future progress with Gated Linear Networks

### ISSUE THREAD

**Issue by aisurfer** [deepmind/deepmind-research#353]
Hello! Sorry for such a question at the Issues.

Guys do you figure out why there is no progress with GLNs research?
Does it fail on most tasks? Or just hard to beat a SOTA?
Why authors or other Deepmind researchers do not continue their work on it?

**Comment by erensezener** [comment]
Hi, 

Apologies for the very late reply!

We are still working on GLNs. In fact, there might be a new GLN paper in the following months :)

> Does it fail on most tasks? Or just hard to beat a SOTA?

It has been my experience that GLNs can solve any task that can be solved with an MLP. GLNs learn faster and forget less compared to an MLP. So they are better suited for online learning generally. GLNs aren't suitable for most computer vision or natural language tasks atm, where you are better off using convolutional nets or transformers.
