### ISSUE TITLE
alphafold_casp13 : the shape of profile_with_prior_without_gap & profile_with_prior

### ISSUE THREAD

**Issue by JieLi-Jessie** [deepmind/deepmind-research#36]
The shape of PSSM generated by PSI-BLAST with BLOUM62 is (NR, 20), there is no X and gap lines. How could  you get the shape with (NR, 21) and (NR,22)?

**Comment by cynthiamao98** [comment]
Following!

**Comment by jennyjli** [comment]
Following!

**Comment by Augustin-Zidek** [comment]
Sorry, the README is not clear about this (I will fix it soon): `profile_with_prior`, `profile_with_prior_without_gap` are computed from the HHBlits multiple sequence alignment.

**Comment by Augustin-Zidek** [comment]
The README has now been updated.
