### ISSUE TITLE
alphafold_casp13: wrong flag for  mutual_information , 'MI' was not used in code, but labeled "√" in feature list

### ISSUE THREAD

**Issue by JieLi-Jessie** [deepmind/deepmind-research#37]
wrong flag for  mutual_information ,  I didn't found 'mutual_information'  in code(only existed in FEATURES, but not been parsed), while it was labeled "Needed" in feature list.

**Comment by Augustin-Zidek** [comment]
Thanks for reporting this issue and sorry I didn't get back to you earlier. 

You are right, we don't use the feature in the model and the README was wrong. This has now been fixed.
