### ISSUE TITLE
Code for Advancing mathematics by guiding human intuition with AI

### ISSUE THREAD

**Issue by casellimarco** [deepmind/deepmind-research#374]
Hello,

I cannot find the code associated to the paper [Advancing mathematics by guiding human intuition with AI](https://www.nature.com/articles/s41586-021-04086-x). In the materials it points towards the deepmind GitHub, without specifying the repo and/or folder.

Where can I find the notebooks?

**Comment by diegolascasas** [comment]
Here:
https://github.com/deepmind/mathematics_conjectures
