### ISSUE TITLE
Updated transporter deps on 22.04 in 2022. Is it worth my time to submit a pull?

### ISSUE THREAD

**Issue by rlewkowicz** [deepmind/deepmind-research#378]
I've had to reset my dev env so many times, and chase deps so many times and I'm wondering if we would accept a pull. At one point, I think I chased all the deps and pinned them properly, my new approach is a little different. 

The ideal, is an update past tf 2.0 but they remove contrib and I'll be honest, it's unlikely I'm going to dig and fix all that. I feel like the middle ground right now is just proper dependency resolution. 

The docs list venv, and I'm using conda, but I don't think that solves the fundamental issue of the pip package not existing. 

This is what I had to do on ubuntu 22.04:
```
sudo apt install -y libhdf5-dev
conda create -y -n transporter python=3.7
conda activate transporter
```

Small changes to the requirements.txt:
```
absl-py==0.7.1
astor==0.7.1
contextlib2==0.5.5
dm-sonnet==1.32
gast==0.2.2
grpcio==1.27.2
h5py==2.9.0
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
Markdown==3.1
mock==3.0.5
numpy==1.16.3
protobuf==3.7.1
semantic-version==2.6.0
six==1.12.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
tensorflow-probability==0.6.0
termcolor==1.1.0
Werkzeug==0.15.4
wrapt==1.11.1
```

Then this is not the prettiest, but again, what can you do with rotting deps? 

```
for i in `cat requirements.txt`; do pip install "$i" || conda install -yc conda-forge  "$i"; done 
```

I'd have to look again, but I think the main thing this fixes is the bad tf versions. 

From here, if the project is interested in a pull, how do you want that formatted? Can I free form the docs and improve the README? Or should I just update the run.sh etc? Is this even acceptable? To use multiple package managers doesn't feel right, but the alternative right now is that this is just broken.

**Comment by rlewkowicz** [comment]
ok, well the tests pass with that, but the notebook doesn't run. I'm sure that's supposed to run on some sort of cloud resource. I have no doubt I can make this work, but that expands the scope of the question about the pull. 

afaik none of this works out of the box anyway. So for me to come out and say "here are the deps for this family of cards, on this os version" I think is better than nothing. I can watch for issues and try to help folks and then tighten and maintain deps etc. 

Before I even try to start on this, I need to know if maintainers are even interested. It wouldnt be the first time I write a big pull just for it to languish. I want to make sure people are interested.

**Comment by diegolascasas** [comment]
Hi Ryan, we don't usually accept PRs. Projects in this repository are meant to snapshots of the code used for the paper and aren't meant to be regularly maintained. Feel free to maintain a fork with the up-to-date deps, and thanks for the offer!

**Comment by yunongLiu1** [comment]
Hello, @rlewkowicz I'm also using Transporter for a few projects, but now I need to upgrade to **tensorflow 2.x** and **sonnet 2.x**, and the dependencies haven't been updated. Have you written any code that could do that? Thanks a lot!!
