### ISSUE TITLE
Learning to simulate: Generating new trajectories on different environments

### ISSUE THREAD

**Issue by raimon-fa** [deepmind/deepmind-research#379]
Hi!

I have trained the model from Learning to Simulate using the WaterRamps dataset. Now I would like to use the trained model in a different environment (different location of sources and walls). I have two questions:

1. How should I code the new environment (where should I write the location of the different solid regions etc.)?
2. Which command should I use to generate the trajectories?

Thank you so much for your help.

**Comment by alvarosg** [comment]
Thanks for the message, unfortunately this code provided as is, but documenting dataset generation is beyond the scope of this reference implementation of the model. 

That said, you may find some of the advice from https://github.com/deepmind/deepmind-research/issues/199 useful.
