### ISSUE TITLE
NeuralNumInt.eval_xc() error

### ISSUE THREAD

**Issue by johTin** [deepmind/deepmind-research#382]
Hi, 
After updating all requirements component and install the last Pyscf Stable release 2.1, i got an error on mf.kernel() " **NeuralNumInt.eval_xc() takes from 3 to 7 positional arguments but 8 were given** ", same with the given example in the web site.
any idea about this error..?

Thanks

**Comment by jsspencer** [comment]
Add `omega=None` to the `NeuralNumInt.eval_xc` method to match the expected interface in pyscf. We'll update this soon.

**Comment by johTin** [comment]
hello [jsspencer](https://github.com/jsspencer)
when I Add omega=None to the NeuralNumInt.eval_xc, I got this error **NeuralNumInt.eval_xc() got an unexpected keyword argument 'omega'** ?
How can I do it ?

**Comment by jsspencer** [comment]
We just pushed changes which add the `omega` keyword to `NeuralNumInt.eval_xc`. Sorry for the delay.
