### ISSUE TITLE
Support for int1e_grids not found and using DM21 for transition metal systems

### ISSUE THREAD

**Issue by Yiwei-data** [deepmind/deepmind-research#383]
Hi, 
    Very happy to know the state of art functional DM21. I am trying to do some benchmark work for transition metal systems using DM21 functional. However, I encountered some problems when using.
1. After I did the example you gave in Readme file, calculating the atomization energy of methane, and it was {'CH4': -40.51785372727111, 'C': -37.84541585423728, 'H': -0.5011533766869017}. The result given on the Readme is {'CH4': -40.51785372584538, 'C': -37.84542045526023, 'H': -0.5011533955627797}. The result is different in the eighth decimal place. I wonder if the error is negligible? But hydrogen doesn't have exactly the same energy.
2. I always find the following warning in my calculations. And I have confirmed that my PySCF version is 2.0. (But when calculating the methane example, it still could give some results. So maybe I need to make sure this warning has to be addressed.）
Computing exx 3000 / 16640 ...
Support for int1e_grids not found (requires libcint 4.4.1 and pyscf 2.0.0a or later. Falling back to slow loop over individual grid points.
3. I found the transition metal systems is hardly to converge even when using B3LYP. So could you please give me some suggestions on what keywords can be added when using DM21 functional or which algorithm (May be Newton?) can be changed to help convergence?

**Comment by jsspencer** [comment]
1. Yes, they're within acceptable limits given convergence thresholds.
2. If you're not compiling libcint and pyscf by hand, you might need to install pyscf 2.0.1, which I believe includes libcint 4.4.6.
3. Newton can help, choice of initial guess can help, stability checks can help. But yes, even B3LYP is tough and converging these systems is notoriously tricky.
