### ISSUE TITLE
Unable to reproduce the reported Pearson Correlation for Enformer 

### ISSUE THREAD

**Issue by Zehui127** [deepmind/deepmind-research#402]
Dear Team,

 I have been working on Enformer model for the last couple of weeks. I extended the original basenji dataset to 196,608 bp and load the fine-tuned Enformer model from "https://tfhub.dev/deepmind/enformer/1". It turns out the pre-trained Enformer only achieved **mean Pearson Correlation** of  0.0384 on the validation dataset. I wonder if reported result in the paper is produced by other pre-trained models? or if certain post-processing is done for producing the result as the following:
![image](https://user-images.githubusercontent.com/17829416/205231850-b72c6386-8eb1-4051-8692-05b82a3d36e7.png)

**Comment by mrevsine** [comment]
Did you figure this out? I'm also having trouble reproducing their correlation scores.

**Comment by Leafy-59** [comment]
Same problem here. Did anyone manage to figure this out?
