### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by 23-aq** [deepmind/deepmind-research#42]
I don't know how to go about this issue. Can you please tell me what i'm doing wrong?

![Screenshot from 2020-03-15 01-07-34](https://user-images.githubusercontent.com/62190106/76691195-776d5d80-6659-11ea-8351-b5852338e405.png)

**Comment by parkitny** [comment]
You need to run from the `deepmind_research` parent directory:

> Then run `alphafold_casp13/run_eval.sh` from the `deepmind_research` parent directory (you will get errors if you try running `run_eval.sh` directly from the `alphafold_casp13` directory).

**Comment by diegolascasas** [comment]
Does this solve your problem?
Closing it for now, feel free to reopen.
