### ISSUE TITLE
problem in parsing hmm_profile feaature file

### ISSUE THREAD

**Issue by fishguysword** [deepmind/deepmind-research#45]
hello ，when I use the hhblit generate the hhm file and use the code here to parse the hhm file ,but 
obvisouly it cannot work ,for the format are bellow:
![image](https://user-images.githubusercontent.com/24436514/79711847-ae3f2f00-82fb-11ea-9e03-b7b897c046d1.png)
the code is 
![image](https://user-images.githubusercontent.com/24436514/79711870-bf883b80-82fb-11ea-8a56-d17322c98e85.png)
it did not match，can you give some help？

**Comment by Augustin-Zidek** [comment]
This is the HHR file (`-o hhr_file_path`) while we use the HHM file (`-ohhm hhm_file_path`).
