### ISSUE TITLE
AlphaFold folding pipeline

### ISSUE THREAD

**Issue by Lorenzo360** [deepmind/deepmind-research#47]
How can you obtain the final (folded) protein 3D structure from the distance map/distogram? In the README it says: 

> pasted/: Contains distograms obtained from the ensembled distograms by pasting. An RR contact map file is computed from this pasted distogram. This is the final distogram that was used in the subsequent AlphaFold folding pipeline in CASP13

But where is this AlphaFold folding pipeline? If this pipeline is not published, are there alternatives? I did not find a satisfactory solution yet.

**Comment by Augustin-Zidek** [comment]
Unfortunately, the actual folding pipeline is not open-sourced. However, the Methods section in the AlphaFold Nature paper (https://rdcu.be/b0mtx) should provide sufficient amount of details to enable reimplementation.

**Comment by monkollek** [comment]
@Lorenzo360 if you are interested I implemented the protein folding part of the pipeline during the holiday break.
https://github.com/leklab/alphafoldv1
as I was interested in reproducing (or close to it) for some of the figures in the Nature publication.
