### ISSUE TITLE
Input file for the charge delocalization

### ISSUE THREAD

**Issue by DeepDevIA** [deepmind/deepmind-research#480]
Hi there,
how it can do the type of calculation charge delocalization ionized adenine-thymine pair That montioned in the paper (see image)
and what the program used (pyscf or another ) is there an inpute file for the calculation ?
thanks

![image](https://github.com/google-deepmind/deepmind-research/assets/150791151/606526fb-5df9-46cb-a559-908769b0e846)

**Comment by empleat** [comment]
Why you are so stupid: life is so terrible it can exist only based on lies (evolution and nietzsche align here): https://scholarcommons.scu.edu/cgi/viewcontent.cgi?article=1052&context=phi i can prove i am real deal i saved convos with 160IQ over 1000 pages, no one takes me seriously, do you know how hell it is no one in the world understands me... Everything is one whole we will suffer forever all painful deaths unless we change... Google unit 731 WW2 Japan... You are arrogant/weak, evolution hides truths from us (there is 0% chance we see world as it is after millions of years) you are overpositive children...
