### ISSUE TITLE
Frobenius norm in AlphaFold pipeline

### ISSUE THREAD

**Issue by couteiral** [deepmind/deepmind-research#53]
Dear AlphaFold team,

I have a question about the `pseudo_frob` feature in AlphaFold. This feature is supposed to be the Frobenius norm of the coupling matrix of each pair of sites in the Potts model. Since the coupling matrix of a site with itself is by definition, the zero matrix (as you can also verify checking the `pseudolikelihood` feature), I would expect the diagonal of the `pseudo_frob` features to be composed of zeros exclusively.

However, this is not what one finds in the published features. For example, for T0953s1:

![image](https://user-images.githubusercontent.com/17805750/83032779-28b34b00-a02e-11ea-8837-cef06aaf5ebe.png)

Would you be able to clarify this?

**Comment by Augustin-Zidek** [comment]
Hi Carlos,

sorry for taking so long to get back to you. 

The reason the diagonal is not zero is that we do also average product correction on the `pseudo_frob` feature:

```python
pseudo_frob = frobenius_norm_no_gaps(pseudolikelihood)
pseudo_frob -= add_apc(pseudo_frob)
```

The `frobenius_norm_no_gaps` function is:

```python
def frobenius_norm_no_gaps(matrix, q=22):
  n = len(matrix) // q
  frob = np.zeros((n, n))
  for i in range(n):
    for j in range(i + 1, n):
      # We only take the frobenius norm of everything apart from the gaps.
      frob[i, j] = 0.5 * (np.linalg.norm(matrix[i*q:i*q+(q-1), j*q:j*q+(q-1)]) +
                          np.linalg.norm(matrix[j*q:j*q+(q-1), i*q:i*q+(q-1)]))
      frob[j, i] = frob[i, j]
  return frob
```

The `add_apc` function is:

```python
def add_apc(matrix):
  row_mean = (matrix.sum(axis=1) - np.diag(matrix)) / (len(matrix) - 1.0)
  if row_mean.mean() != 0.0:
    return np.outer(row_mean, row_mean) / row_mean.mean()
  else:
    return np.zeros(len(matrix), dtype=np.float32)
```

I hope this helps.
