### ISSUE TITLE
The requirements.txt conflicts with itself

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [deepmind/deepmind-research#54]
The requirements file conflicts with itself.

```
ERROR: tensorflow-io 0.8.0 has requirement tensorflow<1.16.0,>=1.15.0, but you'll have tensorflow 1.14.0 which is incompatible.
```
https://github.com/deepmind/deepmind-research/blob/685e16355e39bd4a906fe7ed4749b9e7e5e82b65/scratchgan/requirements.txt#L8

**Comment by HarikrishnanBalagopal** [comment]
Also the scratchgan code doesn't use the GPU. It trains using CPU.

**Comment by mihaelacr** [comment]
This was fixed with [this change](https://github.com/deepmind/deepmind-research/commit/fd75024d61f7e128e923e87c9975be25e72c0e73#diff-f24e843d386d896a7eb790bd67594b66).
