### ISSUE TITLE
error when running run_eval.sh: ModuleNotFoundError: No module named 'alphafold_casp13

### ISSUE THREAD

**Issue by DiejonIA** [deepmind/deepmind-research#64]
Good Afternoon. I'm a biochem student doing some remote research while in quarantine. My prof suggested I use deepmind to study some proteins. I've been going to the process but I'm running into errors when running the run_eval.sh file command line in my ubuntu environment. The error log is below. I'm attaching the run_eval.sh file I'm using and a few screenshots. I hope you can help me. Thank you. Diego Torrejon.  [
[deep_mind error and run_eval file.zip](https://github.com/deepmind/deepmind-research/files/4904979/deep_mind.error.and.run_eval.file.zip)

](url) 

(alphafold) d@DESKTOP-OQPEK4U:/mnt/d/alphafold/deepmind-research-master$ bash /mnt/d/alphafold/deepmind-research-master/deepmind-research-master/alphafold_casp13/run_eval.sh
Requirement already satisfied: wheel in ./alphafold_venv/lib/python3.6/site-packages
Saving output to /home/d/contacts_T1019s2_2020_07_10_14_53_16/
Launching all models for replica 0
Launching all models for replica 1
Launching all models for replica 2
Launching all models for replica 3
Troubleshoot mark 1
All models running, waiting for them to complete
/mnt/d/alphafold/deepmind-research-master/alphafold_venv/bin/python3: Error while finding module specification for 'alphafold_casp13.contacts' (ModuleNotFoundError: No module named 'alphafold_casp13')
/mnt/d/alphafold/deepmind-research-master/alphafold_venv/bin/python3: Error while finding module specification for 'alphafold_casp13.contacts' (ModuleNotFoundError: No module named 'alphafold_casp13')
/mnt/d/alphafold/deepmind-research-master/alphafold_venv/bin/python3: Error while finding module specification for 'alphafold_casp13.contacts' (ModuleNotFoundError: No module named 'alphafold_casp13')
/mnt/d/alphafold/deepmind-research-master/alphafold_venv/bin/python3: Error while finding module specification for 'alphafold_casp13.contacts' (ModuleNotFoundError: No module named 'alphafold_casp13')
/mnt/d/alphafold/deepmind-research-master/alphafold_venv/bin/python3: Error while finding module specification for 'alphafold_casp13.contacts' (ModuleNotFoundError: No module named 'alphafold_casp13')
/mnt/d/alphafold/deepmind-research-master/alphafold_venv/bin/python3: Error while finding module specification for 'alphafold_casp13.contacts' (ModuleNotFoundError: No module named 'alphafold_casp13')
/mnt/d/alphafold/deepmind-research-master/alphafold_venv/bin/python3: Error while finding module specification for 'alphafold_casp13.contacts' (ModuleNotFoundError: No module named 'alphafold_casp13')
/mnt/d/alphafold/deepmind-research-master/alphafold_venv/bin/python3: Error while finding module specification for 'alphafold_casp13.contacts' (ModuleNotFoundError: No module named 'alphafold_casp13')
/mnt/d/alphafold/deepmind-research-master/alphafold_venv/bin/python3: Error while finding module specification for 'alphafold_casp13.contacts' (ModuleNotFoundError: No module named 'alphafold_casp13')
Troubleshoot mark 2
Ensembling all replica outputs
/mnt/d/alphafold/deepmind-research-master/alphafold_venv/bin/python3: Error while finding module specification for 'alphafold_casp13.ensemble_contact_maps' (ModuleNotFoundError: No module named 'alphafold_casp13')

**Comment by Augustin-Zidek** [comment]
Hi Diego, sorry for getting back to you so late. Do you still have the issue? 

I suspect it might be due to launching the `run_eval.sh` script from a wrong directory. Did you follow the steps exactly as described in the README (https://github.com/deepmind/deepmind-research/tree/master/alphafold_casp13#running-the-system)?

> Then run `alphafold_casp13/run_eval.sh` from the `deepmind_research` parent directory (you will get errors if you try running run_eval.sh directly from the `alphafold_casp13` directory).
