### ISSUE TITLE
Deep Compressed Sensing TensorFlow implementation missing CelebA dataset configurations

### ISSUE THREAD

**Issue by PSI497** [deepmind/deepmind-research#77]
I have read the Deep Compressed Sensing paper and the TensorFlow implementation of it in the csgan folder. My goal is to reproduce the results from Table 2 and 3, and I have already added the sensing matrices to the code after posting a question here, and I was able to reproduce the results for the MNIST dataset (Table 2). However, the provided code does not include the CelebA dataset, so I cannot reproduce the results from Table 3 yet. I want to add the CelebA dataset, but I am not sure what the exact setup was to create the results in Table 3. What parameters were used for the dataset (most importantly, the image dimensions), and which generator and discriminator do I need to use to reproduce the results in Table 3?

**Comment by yan-wu** [comment]
Hi, we can't include the CelebA dataset due to legal issue. The settings are the same as Bora et al. 2017, so the images are 32x32 and generator/discriminator are from DC-GAN (which you can obtain from simplifying the provided SN-GAN).

**Comment by PSI497** [comment]
I believe they are using 64x64 images in that paper and the same goes for DC-GAN. Thank you, I will modify the networks then!
