### ISSUE TITLE
Reproducing the Deep Compressed Sensing results

### ISSUE THREAD

**Issue by PSI497** [deepmind/deepmind-research#78]
I could not find the code for testing or validation in the Deep Compressed Sensing paper TensorFlow implementation in the csgan folder. I want to reproduce the results reported in the paper in Table 2 and 3, but in the code I can only see results reported during training, and cannot find a separate testing or validation dataset either. Are the results reported in the tables testing results, and if so, is that included in the provided code?

**Comment by yan-wu** [comment]
We used test split for the numbers in these tables; this part of the code is not provided. You need write your own testing code and use the "test" split of data. See for example get_train_dataset, L197 in utils.py.

**Comment by PSI497** [comment]
Thank you!
