### ISSUE TITLE
How to get the experimental results of mnist test data in the cs_gan and Deep Compressed Sensing? 

### ISSUE THREAD

**Issue by knfriends** [deepmind/deepmind-research#8]
I have two questions
1：How to obtain the experimental results of mnist test set in the paper?  Which .py to run?
2：How to understand the positive and negative signs of the experimental results in the paper? I don't understand what the standard deviation means in the paper.
Thank you very much

**Comment by yan-wu** [comment]
Hi,

1. you can run main_cs.py to train the MLP (best) model. Our code here only provides a guideline, and you may need to modify the code for models other than MLPs.

2. They are standard deviations across image samples, computed from single models.

**Comment by diegolascasas** [comment]
Closing this issue, feel free to reopen it if you have further questions.
